---
name: Horizon Commodities Trading LTD
author: Horizon Commodities Trading
url: "https://horizonct.hk"
company_name: "Horizon Commodities Trading LTD"
registration_no: "3197944"
address: "Suite 1802, Lippo Centre Tower One, 89 Queensway, Hong Kong"
phone: "+971505031984"
email: "info@horizonct.hk"
